dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://192.168.57.188:2181
  protocol:
    #自动寻找端口号
    port: -1
  consumer:
    #启动顺序
    check: false
spring:
  datasource:
    url: jdbc:mysql:///sbd?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


